---
version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: main
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    target-branch: main
    directory: "/"
    schedule:
      interval: monthly
