site_name: FastAPI Türkiye
site_description: FastAPI Türkiye Topluluğu Web Sitesi
site_url: https://hasansezertasan.github.io/fastapi-turkiye/
repo_name: hasansezertasan/fastapi-turkiye
repo_url: https://github.com/hasansezertasan/fastapi-turkiye/
edit_uri: https://github.com/hasansezertasan/fastapi-turkiye/tree/main/docs

theme:
  name: material
  language: tr
  logo: assets/logo-white.svg
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.footer
    - navigation.sections
    - navigation.top
    - navigation.tabs

markdown_extensions:
  - toc:
      permalink: true
      title: İçindekiler
  - abbr
  - admonition
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - def_list

plugins:
  - search
  - blog
  - markdownextradata:
      data: docs/data/
  # - macros:
  #     file: docs/includes/macros.md

nav:
  - Anasayfa: index.md
  - İlerleyiş: progress.md
  - Topluluk: people.md
  - Çeviri Notları: translation-notes.md
  - Rehber: guide.md
  - Sözlük: glossary.md
  - Öğreticiler:
      - Markdown: tutorials/markdown.md
      - MkDocs: tutorials/mkdocs.md
  - Blog: blog

extra_css:
  - css/custom.css

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/fastapiturkiye
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dPgCU2X9xB
    - icon: fontawesome/brands/medium
      link: https://medium.com/fastapi-turkiye
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/9581611/
    - icon: fontawesome/solid/m
      link: https://matrix.to/#/#fastapi-turkiye:matrix.org
