---
name: "Check Branch"
on:
  pull_request:
    branches: ['main']  # Trigger on pull requests to the 'main' branch
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch is valid
        # Use a conditional to ensure the base branch is 'main' and the head branch is not 'dev'
        if: ${{ github.base_ref == 'main' && github.head_ref != 'dev' }}
        run: |
          echo "ERROR: You can only merge to 'main' from 'dev'."
          exit 1
